---
- hosts: suncork
  vars:
    dir: /var/www/suncork
  tasks:
  - name: Fetch repository
    git:
      repo: 'git@github.com:kidandcat/suncork.git'
      dest: "{{ dir }}"
  - name: npm install
    npm:
      path: "{{ dir }}"
  - name: npm run build
    shell: |
      cd /var/www/suncork
      npm run build
  - name: chown www-data
    file:
      path: "{{ dir }}"
      recurse: yes
      owner: www-data